Repository reactphp/child-process, pull requests merged in 2019-01, with the labels that each got.

#66 Test against PHP7.2 and PHP 7.3, improve HHVM compatibility and add forward compatibility with PHPUnit 7
  .travis.yml
  composer.json
  phpunit.xml.dist
  src/Process.php
  tests/AbstractProcessTest.php
Labels: easy pick, maintenance

#67 Support spawning child process on Windows without process I/O pipes
  README.md
  composer.json
  examples/01-stdio.php
  examples/02-race.php
  examples/03-stdout-stderr.php
  examples/04-terminate.php
  examples/11-benchmark-read.php
  examples/12-benchmark-write.php
  examples/13-benchmark-throughput.php
  examples/21-fds.php
  examples/22-race-exit.php
  examples/23-forward-socket.php
  src/Process.php
  tests/AbstractProcessTest.php
Labels: new feature

#68 Improve performance by prefixing all global functions calls with \ to skip the look up and resolve process and go straight to the global function
  src/Process.php
Labels: easy pick, help wanted, maintenance

#71 Run tests on Windows via Travis CI
  .travis.yml
Labels: maintenance
